"""Add vendor contracts and penalty notes

Revision ID: 887069d8a976
Revises: 011
Create Date: 2026-08-05 23:07:54.299778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '887069d8a976'
down_revision: Union[str, None] = '011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('contract_code', sa.String(length=50), nullable=False),
    sa.Column('station_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('penalty_per_sla_hour', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_penalty_cap', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['issue_categories.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_contracts_contract_code'), 'vendor_contracts', ['contract_code'], unique=True)
    op.create_table('vendor_penalty_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('penalty_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('clause_reference', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('pdf_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['vendor_contracts.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('comments', 'is_hidden',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('comments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('divisions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('divisions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('divisions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_emergency_alerts_station_active', table_name='emergency_alerts')
    op.alter_column('issue_categories', 'default_severity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('issue_categories', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('issue_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('issue_photos', 'scan_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('issue_photos', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('issue_photos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('issue_supports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('issue_timeline_events', 'visibility',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('issue_timeline_events', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('issue_timeline_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_timeline_issue_created', table_name='issue_timeline_events')
    op.alter_column('issues', 'severity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('issues', 'support_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('issues', 'comment_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('issues', 'priority_score',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=False)
    op.alter_column('issues', 'trending_score',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               nullable=False)
    op.alter_column('issues', 'is_emergency',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('issues', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('issues', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('issues', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_issues_created_at', table_name='issues')
    op.drop_index('idx_issues_embedding_hnsw', table_name='issues', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index('idx_issues_station_priority', table_name='issues')
    op.drop_index('ix_issues_embedding_hnsw', table_name='issues', postgresql_using='hnsw')
    op.drop_index('ix_issues_public_priority', table_name='issues')
    op.drop_index('ix_issues_station_public_status', table_name='issues')
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_notifications_user_read_created', table_name='notifications')
    op.alter_column('otp_requests', 'attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('otp_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('platforms', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('stations', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('stations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('stations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('system_config', 'value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('system_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_roles', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'preferred_language',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    op.alter_column('users', 'is_anonymous',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('zones', 'country_code',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.alter_column('zones', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('zones', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('zones', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zones', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('zones', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('zones', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('zones', 'country_code',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_anonymous',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'preferred_language',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('user_roles', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('system_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('system_config', 'value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('stations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stations', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('platforms', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('otp_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('otp_requests', 'attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_notifications_user_read_created', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index('ix_issues_station_public_status', 'issues', ['station_id', 'is_public', 'status'], unique=False)
    op.create_index('ix_issues_public_priority', 'issues', ['is_public', 'priority_score'], unique=False)
    op.create_index('ix_issues_embedding_hnsw', 'issues', ['embedding'], unique=False, postgresql_using='hnsw')
    op.create_index('idx_issues_station_priority', 'issues', ['station_id', 'priority_score'], unique=False)
    op.create_index('idx_issues_embedding_hnsw', 'issues', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index('idx_issues_created_at', 'issues', ['created_at'], unique=False)
    op.alter_column('issues', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('issues', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('issues', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('issues', 'is_emergency',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('issues', 'trending_score',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               nullable=True)
    op.alter_column('issues', 'priority_score',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=True)
    op.alter_column('issues', 'comment_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('issues', 'support_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('issues', 'severity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('idx_timeline_issue_created', 'issue_timeline_events', ['issue_id', 'created_at'], unique=False)
    op.alter_column('issue_timeline_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('issue_timeline_events', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('issue_timeline_events', 'visibility',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('issue_supports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('issue_photos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('issue_photos', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('issue_photos', 'scan_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('issue_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('issue_categories', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('issue_categories', 'default_severity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_emergency_alerts_station_active', 'emergency_alerts', ['station_id', 'is_active'], unique=False)
    op.alter_column('divisions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('divisions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('divisions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('comments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('comments', 'is_hidden',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_table('vendor_penalty_notes')
    op.drop_index(op.f('ix_vendor_contracts_contract_code'), table_name='vendor_contracts')
    op.drop_table('vendor_contracts')
    # ### end Alembic commands ###
